import { db } from '@/lib/db';
import { NextRequest, NextResponse } from 'next/server';
import { sendPushToAll } from '@/lib/push';
import { jakartaToday, jakartaDateString, jakartaMonthString } from '@/lib/timezone';
export async function GET(request: NextRequest) {
  try { const cs = process.env.CRON_SECRET; if (process.env.NODE_ENV === 'production' && !cs) return NextResponse.json({ error: 'No CRON_SECRET' }, { status: 500 }); if (cs && request.headers.get('authorization') !== `Bearer ${cs}`) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    if (!(await db.pushSubscription.count())) return NextResponse.json({ sent: 0 });
    const s = await db.appSettings.findFirst(); if (!s) return NextResponse.json({ sent: 0 });
    const today = jakartaToday(); const ts = jakartaDateString(); const mk = jakartaMonthString(); const res: string[] = [];
    if (s.pushHabitEnabled) { const h = await db.habit.findMany({ where: { status: 'active', targetType: 'daily', startDate: { lte: today } }, select: { id: true } }); if (h.length) { const l = await db.habitLog.findMany({ where: { date: { gte: new Date(ts+'T00:00:00Z'), lte: new Date(ts+'T23:59:59Z') }, completed: true }, select: { habitId: true } }); const c = new Set(l.map(x=>x.habitId)); const inc = h.filter(x=>!c.has(x.id)).length; if (inc>0) { await sendPushToAll({title:'🌱 Rutina',body:`${inc} habit belum selesai.`,tag:'habit',url:'/?tab=track'}); res.push('habit'); } } }
    if (s.pushBudgetEnabled) { const BM=7*3600000; const ms=new Date(today.getFullYear(),today.getMonth(),1); const me=new Date(today.getFullYear(),today.getMonth()+1,0,23,59,59); const bs=await db.budget.findMany(); const EX=new Set(['Transfer Antar Sumber','Penyesuaian Saldo']); for(const b of bs){const tx=await db.transaction.findMany({where:{date:{gte:new Date(ms.getTime()-BM),lte:new Date(me.getTime()+BM)},type:'expense',category:b.category}});const mt=tx.filter(t=>{const m=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit'}).format(new Date(t.date));return m===mk&&!EX.has(t.category)});const sp=mt.reduce((a,t)=>a+t.amount,0);const p=b.amount>0?(sp/b.amount)*100:0;if(p>=100){await sendPushToAll({title:'⚠️ Budget',body:`${b.category} ${Math.round(p)}%`,tag:`bo-${b.category}`,url:'/?tab=finance',requireInteraction:true});res.push('bo');}else if(p>=85){await sendPushToAll({title:'💡 Budget',body:`${b.category} ${Math.round(p)}%`,tag:`bw-${b.category}`,url:'/?tab=finance'});res.push('bw');}}}
    if (s.pushSpendingEnabled) { const BM=7*3600000; const te=await db.transaction.findMany({where:{date:{gte:new Date(new Date(ts+'T00:00:00Z').getTime()-BM),lte:new Date(new Date(ts+'T23:59:59Z').getTime()+BM)},type:'expense'}}); const EX=new Set(['Transfer Antar Sumber','Penyesuaian Saldo']); const rt=te.filter(t=>{const d=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date(t.date));return d===ts&&!EX.has(t.category)}); if(rt.length){const tot=rt.reduce((a,t)=>a+t.amount,0);await sendPushToAll({title:'💰 Spending',body:`Habis ${new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',minimumFractionDigits:0}).format(tot)} dari ${rt.length} tx.`,tag:'spending',url:'/?tab=finance'});res.push('spending');} }
    return NextResponse.json({ success: true, results: res });
  } catch(e) { return NextResponse.json({ error: 'Failed' }, { status: 500 }); }
}
