// Extracted from src/app/api/learning/article/route.ts — search query templates per topic.

// 15+ queries per default topic, 5+ generic templates.

export const TOPIC_QUERIES: Record<string, string[]> = {
  Akuntansi: [
    'prinsip akuntansi dasar indonesia terbaru',
    'cara membuat jurnal umum akuntansi',
    'laporan keuangan perusahaan contoh',
    'neraca saldo dan penyesuaian akuntansi',
    'akuntansi biaya pengertian dan contoh',
    'standar akuntansi keuangan PSAK terbaru',
    'akuntansi manajemen vs keuangan perbedaan',
    'audit internal perusahaan prosedur',
    'akuntansi forensic fraud detection',
    'depresiasi amortisasi penjelasan lengkap',
    'accrual basis vs cash basis akuntansi',
    'working capital management akuntansi',
    'akuntansi perpajakan dasar Indonesia',
    'cash flow statement analisis',
    'reconciliation bank rekonsiliasi bank',
    'budgeting perusahaan teknik penyusunan',
    'akuntansi sektor publik pemerintahan',
    'activity based costing contoh',
  ],
  Keuangan: [
    'manajemen keuangan pribadi strategi',
    'cara membuat anggaran bulanan efektif',
    'investasi reksa dana pemula panduan',
    'bunga majemuk perhitungan contoh',
    'literasi keuangan Indonesia OJK',
    'dana darurat berapa jumlah ideal',
    'pinjaman online legal vs ilegal',
    'kredit skor Indonesia pengertian',
    'financial planning pernikahan indonesia',
    'keuangan syariah produk perbankan',
    'diversifikasi portofolio investasi',
    'inflasi dampak terhadap keuangan',
    'asuransi jiwa kesehatan perbedaan',
    'cicilan KPR tips memilih',
    'tabungan vs deposito vs reksadana',
    ' fintech indonesia perkembangan 2024',
    'perencanaan pajak keuangan personal',
    'emergency fund strategi membangun',
  ],
  Ekonomi: [
    'pengertian GDP PNB Indonesia terbaru',
    'inflasi Indonesia penyebab dan dampak',
    'supply dan demand contoh nyata',
    'ekonomi makro vs mikro perbedaan',
    'kebijakan moneter Bank Indonesia',
    'fiscal policy pemerintah indonesia',
    'ekonomi digital indonesia pertumbuhan',
    'UEU usaha mikro kecil menengah',
    'kurva Phillips inflasi pengangguran',
    'ekonomi kreatif indonesia potensi',
    'foreign direct investment FDI indonesia',
    'negara maju vs berkembang ciri',
    'ekonomi pasar bebas vs terencana',
    'harga minyak dampak ekonomi global',
    'perdagangan internasional manfaat',
    'OJK peran fungsi regulasi',
    'ekonomi pancasila prinsip dasar',
    'market structure persaingan sempurna',
    'ekonomi perilaku behavioral economics',
    'kemiskinan inequality Indonesia data',
  ],
  Pajak: [
    'panduan PPh 21 karyawan terbaru',
    'cara menghitung PPN perusahaan',
    'SPT tahunan cara lapor online',
    'NPWP pendaftaran cara dan syarat',
    'pajak penghasilan tarif progresif',
    'tax planning strategi legal',
    'pajak UMKM insentif dan keringanan',
    'e-filing DJP Online tutorial lengkap',
    'pajak digital economy regulasi',
    'transfer pricing aturan internasional',
    'pajak properti PBB dan BPHTB',
    'pajak deklarasi amnesty program',
    'self assessment system pajak',
    'konsultan pajak kapan butuh',
    'pajak ekspor impor bea cukai',
    'pajak crypto aset kripto aturan',
    'tax amnesty jilid 3 berita',
    'faktur pajak elektronik e-Faktur',
  ],
  Investasi: [
    'cara investasi saham pemula indonesia',
    'analisis fundamental saham langkah',
    'reksa dana pasar uang vs saham',
    'investasi emas keuntungan risiko',
    'portofolio investasi diversifikasi',
    'IPO saham peluang dan risiko',
    'investasi properti strategi jangka panjang',
    ' ETF exchange traded fund indonesia',
    'P2P lending investasi fintech',
    'analisis teknikal saham dasar',
    'investasi obligasi surat berharga negara',
    'dividen saham pengertian dan contoh',
    'margin trading saham risiko',
    'investasi startup equity crowdfunding',
    'rebalancing portofolio strategi',
    'warren buffett prinsip investasi value',
    'investasi syariah sukuk dan reksa',
    'crypto bitcoin ethereum regulasi indonesia',
    'dollar cost averaging DCA strategi',
    'smart beta investing strategi',
  ],
  Manajemen: [
    'prinsip manajemen henry fayol',
    'leadership styles gaya kepemimpinan',
    'manajemen proyek agile scrum',
    'strategic planning proses perencanaan',
    'manajemen SDM sumber daya manusia',
    'marketing mix 7P strategi pemasaran',
    'manajemen risiko framework enterprise',
    'team building aktivitas efektif',
    'manajemen perubahan change management',
    'decision making proses pengambilan',
    'KPI OKR perbedaan implementasi',
    'manajemen operasional efisiensi',
    'remote work manajemen tim jarak jauh',
    'manajemen konflik di tempat kerja',
    'entrepreneurship kewirausahaan dasar',
    'manajemen stres burnout kerja',
    'balanced scorecard implementasi',
  ],
  default: [
    'materi {topic} dasar untuk pemula',
    'pengertian {topic} dalam bahasa indonesia',
    'konsep {topic} aplikasi nyata',
    'belajar {topic} tips cepat',
    'tantangan {topic} di Indonesia',
    'perkembangan {topic} terbaru 2024',
    '{topic} studi kasus Indonesia',
    'karir {topic} peluang profesi',
    'tools {topic} software terbaik',
    '{topic} vs alternatif perbandingan',
    '{topic} tren global 2024',
    '{topic} risiko dan peluang',
    'mahasiswa belajar {topic} panduan',
  ],
};

export function getSearchQueries(topic: string): string[] {
  const specific = TOPIC_QUERIES[topic];
  if (specific) return specific;
  return TOPIC_QUERIES.default.map(q => q.replace('{topic}', topic));
}
