// Extracted from dashboard.tsx — default empty-state data for the dashboard.
import type { DashboardData } from './dashboard-types';

export const DEFAULT_DATA: DashboardData = {
  totalHabits: 0,
  completionRate: 0,
  currentStreak: 0,
  longestStreak: 0,
  successToday: 0,
  weeklyCompletion: 0,
  monthlyCompletion: 0,
  bestHabit: { name: 'N/A', icon: '🏆', rate: 0 },
  worstHabit: { name: 'N/A', icon: '📉', rate: 0 },
  totalXP: 0,
  currentLevel: 1,
  nextLevelXP: 100,
  currentLevelXP: 0,
  levelProgress: 0,
  goalProgress: 0,
  moodAverage: '3.0',
  sleepAverage: '7.0',
  productivityScore: 0,
  weeklyChartData: [],
  monthlyChartData: [],
  categoryPerformance: [],
  todayFocus: [],
  period: 'all',
  habitDetailStats: [],
  stackedBarData: [],
  weeklyPattern: [],
  financeOverview: { totalIncome: 0, totalExpense: 0, netBalance: 0, transactionCount: 0, budgetWarning: 0, budgetExceeded: 0 },
  timeTrackedSummary: [],
  lastDoneSummary: [],
};
