'use client';
import { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Bell, BellOff, Check, Loader2, Send, Clock, Wallet, TrendingDown } from 'lucide-react';
import { toast } from 'sonner';
type PS = 'default'|'granted'|'denied'|'unsupported';
function b64(t:string){const p='='.repeat((4-(t.length%4))%4);const b=(t+p).replace(/-/g,'+').replace(/_/g,'/');const r=atob(b);const o=new Uint8Array(r.length);for(let i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return new Uint8Array(o.buffer.slice(0) as ArrayBuffer);}
export function PushNotificationSettings(){
  const [perm,setPerm]=useState<PS>('default');const [sub,setSub]=useState(false);const [load,setLoad]=useState(false);const [test,setTest]=useState(false);const [sav,setSav]=useState(false);
  const vk=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
  const [he,setHe]=useState(true);const[ht,setHt]=useState('08:00');const[be,setBe]=useState(true);const[bt,setBt]=useState('12:00');const[se,setSe]=useState(true);const[st,setSt]=useState('20:00');
  useEffect(()=>{if(typeof window==='undefined')return;if(!('serviceWorker'in navigator)||!('PushManager'in window)){setPerm('unsupported');return;}const p=Notification.permission;if(p==='granted'||p==='denied'||p==='default')setPerm(p);navigator.serviceWorker.ready.then(r=>r.pushManager.getSubscription()).then(s=>setSub(!!s)).catch(()=>{});fetch('/api/settings').then(r=>r.json()).then(d=>{if(d.pushHabitTime)setHt(d.pushHabitTime);if(d.pushHabitEnabled!==undefined)setHe(d.pushHabitEnabled);if(d.pushBudgetTime)setBt(d.pushBudgetTime);if(d.pushBudgetEnabled!==undefined)setBe(d.pushBudgetEnabled);if(d.pushSpendingTime)setSt(d.pushSpendingTime);if(d.pushSpendingEnabled!==undefined)setSe(d.pushSpendingEnabled);}).catch(()=>{});},[]);
  const save=useCallback(async()=>{setSav(true);try{const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({pushHabitEnabled:he,pushHabitTime:ht,pushBudgetEnabled:be,pushBudgetTime:bt,pushSpendingEnabled:se,pushSpendingTime:st})});if(!r.ok)throw new Error('f');toast.success('Jadwal disimpan!');}catch{toast.error('Gagal simpan.');}finally{setSav(false);}},[he,ht,be,bt,se,st]);
  const subFn=useCallback(async()=>{setLoad(true);try{if(!vk||vk.length<50){toast.error('VAPID key belum dikonfigurasi.');return;}let r:ServiceWorkerRegistration;try{r=await Promise.race([navigator.serviceWorker.ready,new Promise<never>((_,re)=>setTimeout(()=>re(new Error('TO')),5000))]);}catch{await navigator.serviceWorker.register('/sw.js');r=await navigator.serviceWorker.ready;}const p=await Notification.requestPermission();if(p!=='granted'){toast.error('Permission ditolak.');setPerm('denied');return;}setPerm('granted');const s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(vk) as BufferSource});const sj=s.toJSON();const res=await fetch('/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:sj.endpoint,keys:sj.keys,userAgent:navigator.userAgent})});if(!res.ok){const e=await res.json().catch(()=>({}));throw new Error(e.error||`S${res.status}`);}setSub(true);toast.success('Aktif! Klik Test.');}catch(e){try{const r=await navigator.serviceWorker.ready;const s=await r.pushManager.getSubscription();if(s)await s.unsubscribe();}catch{}setSub(false);console.error('Push subscribe failed:',e);const m=e instanceof Error?e.message:String(e);if(m.includes('TO'))toast.error('SW belum siap. Refresh halaman lalu coba lagi.');else if(m.includes('VAPID')||m.includes('key'))toast.error('VAPID bermasalah. Hubungi admin.');else if(m.includes('push service error')||m.includes('Registration failed'))toast.error('Gagal daftar ke push service. Coba refresh & aktifkan lagi. Jika tetap gagal, coba non-incognito mode atau browser lain (Chrome/Firefox terbaru).');else toast.error(`Gagal: ${m}`);}finally{setLoad(false);}},[vk]);
  const unsub=useCallback(async()=>{setLoad(true);try{const r=await navigator.serviceWorker.ready;const s=await r.pushManager.getSubscription();if(s){await fetch(`/api/push/subscribe?endpoint=${encodeURIComponent(s.endpoint)}`,{method:'DELETE'});await s.unsubscribe();}setSub(false);toast.success('Dinonaktifkan.');}catch{toast.error('Gagal.');}finally{setLoad(false);}},[]);
  const testFn=useCallback(async()=>{setTest(true);try{const r=await fetch('/api/push/test',{method:'POST'});const d=await r.json();if(d.success)toast.success(`Terkirim ke ${d.sent} device!`);else toast.error(d.error||'Gagal.');}catch(e){toast.error(`Gagal: ${e instanceof Error?e.message:''}`);}finally{setTest(false);}},[]);
  if(perm==='unsupported')return(<Card className="border-dashed"><CardContent className="p-4 flex items-center gap-3"><BellOff className="h-5 w-5 text-muted-foreground shrink-0"/><div><p className="text-sm font-medium">Notifikasi Push</p><p className="text-xs text-muted-foreground mt-0.5">Tidak didukung. Coba Chrome Android atau PWA iOS 16.4+.</p></div></CardContent></Card>);
  return(<Card><CardContent className="p-4 space-y-3"><div className="flex items-center gap-3"><div className="shrink-0">{sub?<div className="w-10 h-10 rounded-full bg-green-500/10 flex items-center justify-center"><Check className="h-5 w-5 text-green-600"/></div>:<div className="w-10 h-10 rounded-full bg-muted/40 flex items-center justify-center"><Bell className="h-5 w-5 text-muted-foreground"/></div>}</div><div className="flex-1 min-w-0"><p className="text-sm font-medium">Notifikasi Push</p><p className="text-xs text-muted-foreground mt-0.5">{sub?'Aktif. Klik Test untuk cek.':'Aktifkan untuk reminder harian.'}</p></div><Button size="sm" variant={sub?'outline':'default'} onClick={sub?unsub:subFn} disabled={load||perm==='denied'} className="shrink-0">{load&&<Loader2 className="h-4 w-4 mr-1 animate-spin"/>}{sub?'Nonaktifkan':'Aktifkan'}</Button></div>{sub&&(<><div className="flex gap-2 pt-1 border-t border-border/50"><Button size="sm" variant="outline" onClick={testFn} disabled={test} className="w-full">{test?<Loader2 className="h-4 w-4 mr-1.5 animate-spin"/>:<Send className="h-4 w-4 mr-1.5"/>}{test?'Mengirim...':'Test Notifikasi'}</Button></div><div className="space-y-3 pt-2 border-t border-border/50"><div className="flex items-center gap-1.5"><Clock className="h-3.5 w-3.5 text-muted-foreground"/><p className="text-xs font-semibold text-muted-foreground uppercase">Jadwal Notifikasi</p></div><div className="flex items-center gap-2 p-2 rounded-lg bg-muted/30"><Bell className="h-4 w-4 text-primary shrink-0"/><div className="flex-1 min-w-0"><p className="text-xs font-medium">Reminder Habit</p><p className="text-[10px] text-muted-foreground">Habit belum selesai</p></div><Input type="time" value={ht} onChange={e=>setHt(e.target.value)} className="w-24 h-8 text-xs" disabled={!he}/><Switch checked={he} onCheckedChange={setHe}/></div><div className="flex items-center gap-2 p-2 rounded-lg bg-muted/30"><Wallet className="h-4 w-4 text-amber-600 shrink-0"/><div className="flex-1 min-w-0"><p className="text-xs font-medium">Alert Budget</p><p className="text-[10px] text-muted-foreground">Budget mendekati limit</p></div><Input type="time" value={bt} onChange={e=>setBt(e.target.value)} className="w-24 h-8 text-xs" disabled={!be}/><Switch checked={be} onCheckedChange={setBe}/></div><div className="flex items-center gap-2 p-2 rounded-lg bg-muted/30"><TrendingDown className="h-4 w-4 text-red-500 shrink-0"/><div className="flex-1 min-w-0"><p className="text-xs font-medium">Spending</p><p className="text-[10px] text-muted-foreground">Pengeluaran hari ini</p></div><Input type="time" value={st} onChange={e=>setSt(e.target.value)} className="w-24 h-8 text-xs" disabled={!se}/><Switch checked={se} onCheckedChange={setSe}/></div><Button size="sm" onClick={save} disabled={sav} className="w-full">{sav&&<Loader2 className="h-4 w-4 mr-1.5 animate-spin"/>}Simpan Jadwal</Button></div></>)}</CardContent></Card>);
}
